AWSTemplateFormatVersion: 2010-09-09

Mappings: 
#####
# RegionMpas
#####
  RegionMap: 
    us-east-1:
      a: "us-east-1a"
      c: "us-east-1c"
      d: "us-east-1d"

    us-west-2:
      a: "us-west-2a"
      c: "us-west-2c"
      d: "us-west-2d"

    ap-northeast-1: #Tokyo
      a: "ap-northeast-1a"
      c: "ap-northeast-1c"
      d: "ap-northeast-1d"
 

Resources: 
#######
# VPC
#######
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: myVPC

######
# InternetGW
######
  internetGW:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: internetGW

#####
# AttachInternetGateway
#####      
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref internetGW

#####
# PublicSubnet00
#####
  PublicSubnet00:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", a]
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: PublicSubnet00

#####
# PublicSubnet02
#####
  PublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", c]
      VpcId: !Ref myVPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: PublicSubnet02

#####
# PrivateSubnet01
#####
  PrivateSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", a]
      VpcId: !Ref myVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet01

#####
# PrivateSubnet03
#####
  PrivateSubnet03:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", c]
      VpcId: !Ref myVPC
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet03     

#####
# NatGateway
#####
  NatGW:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt EIpNatGW.AllocationId
      SubnetId: !Ref publicsubnet00
      Tags:
        - Key: Name
          Value: NatGW
  EIpNatGW:
    Type: AWS::EC2::EIP 
    Properties:
      Domain: vpc


#####
# OutputSection
#####
Outputs:
    VPC:
      Value: !Ref myVPC
      Export:
        Name: VPCId
    internetGW:
      Value: !Ref internetGW
      Export:
        Name: internetGW
    PublicSubnet00:
      Value: !Ref PublicSubnet00
      Export: 
        Name: PublicSubnet00
    PrivateSubnet01:
      Value: !Ref PrivateSubnet01
      Export: 
        Name: PrivateSubnet01
    PublicSubnet02:
      Value: !Ref PublicSubnet02
      Export: 
        Name: PublicSubnet02
    PrivateSubnet03:
      Value: !Ref PrivateSubnet03
      Export: 
        Name: PrivateSubnet03
    NatGW:
      Value: !Ref NatGW
      Export:
        Name: NatGWId
