AWSTemplateFormatVersion: 2010-09-09

Mappings: 
  RegionMap: 
    us-east-1:
      a: "us-east-1a"
      c: "us-east-1c"
      d: "us-east-1d"

    us-west-2:
      a: "us-west-2a"
      C: "us-west-2c"
      d: "us-west-2d"

    ap-northeast-1:
      a: "ap-northeast-1a"
      c: "ap-northeast-1c"
      d: "ap-northeast-1d"



Resources: 
#######
# VPC
#######
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: myVPC

######
# InternetGW
######
  internetGW:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: internetGW

#####
# AttachInternetGateway
#####      
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref internetGW

#####
# PublicSubnet
#####
  publicsubnet00:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", a]
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: PublicSubnet00

#####
# PrivateSubnet
#####
  privatesubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", c]
      VpcId: !Ref myVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnet01

#####
# OutputSection
#####
Outputs:
    VPC:
      Value: !Ref myVPC
      Export:
        Name: VPCId
    PublicSubnet00:
      Value: !Ref publicsubnet00
      Export: 
        Name: PublicSubnet00
    PrivateSubnet01:
      Value: !Ref privatesubnet01
      Export: 
        Name: PrivateSubnet01
    internetGW:
      Value: !Ref internetGW
      Export:
        Name: internetGW